# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_userfollowers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=20)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profiles.User')),
            ],
        ),
    ]
